// 카테고리별 단어 사전
// 각 단어는 한글로 작성, 게임에서 자동으로 초성을 추출합니다.
const WORD_DATA = {
  food: {
    name: '음식',
    emoji: '🍔',
    words: [
      { word: '김치찌개', hint: '얼큰한 국물 요리' },
      { word: '비빔밥', hint: '여러 재료를 비벼 먹어요' },
      { word: '떡볶이', hint: '빨갛고 매콤한 분식' },
      { word: '불고기', hint: '달콤한 양념 고기 요리' },
      { word: '삼겹살', hint: '구워 먹는 돼지고기 부위' },
      { word: '잡채', hint: '당면이 들어간 명절 음식' },
      { word: '갈비탕', hint: '소갈비를 푹 끓인 탕' },
      { word: '순두부찌개', hint: '부드러운 두부 찌개' },
      { word: '돈가스', hint: '튀긴 돼지고기' },
      { word: '치킨', hint: '맥주와 환상의 짝꿍' },
      { word: '피자', hint: '둥근 이탈리아 음식' },
      { word: '햄버거', hint: '패티가 들어간 빵' },
      { word: '라면', hint: '꼬불꼬불한 면' },
      { word: '냉면', hint: '시원하게 먹는 면 요리' },
      { word: '김밥', hint: '소풍 단골 메뉴' },
      { word: '된장찌개', hint: '구수한 한국 전통 찌개' },
      { word: '제육볶음', hint: '매콤한 돼지고기 볶음' },
      { word: '닭갈비', hint: '춘천이 유명해요' },
      { word: '삼계탕', hint: '여름 보양식' },
      { word: '곱창', hint: '소나 돼지의 작은 창자' },
      { word: '설렁탕', hint: '뽀얀 국물의 소고기 탕' },
      { word: '짜장면', hint: '검은 소스의 중식' },
      { word: '짬뽕', hint: '빨간 국물의 중식 면' },
      { word: '탕수육', hint: '바삭한 고기에 소스를' },
      { word: '초밥', hint: '일본 대표 음식' },
    ],
  },
  animal: {
    name: '동물',
    emoji: '🐶',
    words: [
      { word: '강아지', hint: '멍멍 짖어요' },
      { word: '고양이', hint: '야옹 울어요' },
      { word: '코끼리', hint: '긴 코를 가진 큰 동물' },
      { word: '기린', hint: '목이 매우 길어요' },
      { word: '호랑이', hint: '한국의 상징 동물' },
      { word: '사자', hint: '동물의 왕' },
      { word: '원숭이', hint: '바나나를 좋아해요' },
      { word: '너구리', hint: '눈에 까만 줄무늬' },
      { word: '다람쥐', hint: '도토리를 모아요' },
      { word: '토끼', hint: '깡총깡총 뛰어요' },
      { word: '거북이', hint: '느리지만 오래 살아요' },
      { word: '악어', hint: '강에 사는 무서운 파충류' },
      { word: '독수리', hint: '하늘의 제왕' },
      { word: '펭귄', hint: '남극에 살아요' },
      { word: '북극곰', hint: '북극에 사는 흰 곰' },
      { word: '판다', hint: '대나무를 먹는 흑백 동물' },
      { word: '캥거루', hint: '주머니에 새끼를 키워요' },
      { word: '코알라', hint: '유칼립투스를 먹어요' },
      { word: '하마', hint: '물에서 사는 큰 동물' },
      { word: '공작', hint: '화려한 꼬리 깃털' },
      { word: '햄스터', hint: '볼주머니가 큰 작은 동물' },
      { word: '낙타', hint: '사막의 배' },
      { word: '돌고래', hint: '똑똑한 바다 포유류' },
      { word: '상어', hint: '바다의 무서운 포식자' },
      { word: '문어', hint: '다리가 8개인 바다생물' },
    ],
  },
  country: {
    name: '나라',
    emoji: '🌏',
    words: [
      { word: '대한민국', hint: '우리나라' },
      { word: '미국', hint: '성조기의 나라' },
      { word: '일본', hint: '벚꽃의 나라' },
      { word: '중국', hint: '만리장성이 있는 나라' },
      { word: '프랑스', hint: '에펠탑이 있는 나라' },
      { word: '독일', hint: '맥주와 소시지' },
      { word: '영국', hint: '빅벤이 있는 나라' },
      { word: '이탈리아', hint: '피자와 파스타' },
      { word: '스페인', hint: '플라멩코와 투우' },
      { word: '러시아', hint: '세계에서 가장 넓은 나라' },
      { word: '브라질', hint: '삼바와 아마존' },
      { word: '캐나다', hint: '단풍잎 국기' },
      { word: '호주', hint: '캥거루의 나라' },
      { word: '인도', hint: '타지마할이 있는 나라' },
      { word: '태국', hint: '똠얌꿍의 나라' },
      { word: '베트남', hint: '쌀국수가 유명' },
      { word: '필리핀', hint: '7천여 개 섬의 나라' },
      { word: '싱가포르', hint: '동남아 작은 도시국가' },
      { word: '터키', hint: '동서양이 만나는 나라' },
      { word: '이집트', hint: '피라미드의 나라' },
      { word: '그리스', hint: '신화의 나라' },
      { word: '네덜란드', hint: '풍차와 튤립' },
      { word: '스위스', hint: '알프스의 나라' },
      { word: '멕시코', hint: '타코의 나라' },
      { word: '아르헨티나', hint: '탱고의 나라' },
    ],
  },
  sport: {
    name: '스포츠',
    emoji: '⚽',
    words: [
      { word: '축구', hint: '월드컵' },
      { word: '야구', hint: '한국시리즈' },
      { word: '농구', hint: 'NBA' },
      { word: '배구', hint: '네트 너머로 공을 보내요' },
      { word: '테니스', hint: '윔블던' },
      { word: '탁구', hint: '작은 공으로 하는 운동' },
      { word: '배드민턴', hint: '셔틀콕을 사용해요' },
      { word: '골프', hint: '홀에 공을 넣어요' },
      { word: '수영', hint: '물에서 하는 운동' },
      { word: '권투', hint: '글러브를 끼고 싸워요' },
      { word: '태권도', hint: '한국의 무술' },
      { word: '유도', hint: '메치는 무술' },
      { word: '검도', hint: '죽도를 사용하는 무술' },
      { word: '체조', hint: '평균대와 마루 운동' },
      { word: '육상', hint: '달리기와 던지기' },
      { word: '스키', hint: '눈 위를 미끄러져요' },
      { word: '스노보드', hint: '한 발로 타는 겨울 스포츠' },
      { word: '컬링', hint: '얼음 위 빗자루 스포츠' },
      { word: '피겨스케이팅', hint: '김연아의 종목' },
      { word: '양궁', hint: '한국의 효자 종목' },
      { word: '사격', hint: '표적을 맞히는 스포츠' },
      { word: '펜싱', hint: '검을 사용하는 스포츠' },
      { word: '럭비', hint: '타원형 공을 사용해요' },
      { word: '미식축구', hint: '슈퍼볼' },
      { word: '핸드볼', hint: '손으로 하는 구기' },
    ],
  },
  movie: {
    name: '영화',
    emoji: '🎬',
    words: [
      { word: '기생충', hint: '봉준호 감독의 아카데미 수상작' },
      { word: '명량', hint: '이순신 장군의 해전' },
      { word: '극한직업', hint: '치킨집을 차린 형사들' },
      { word: '신과함께', hint: '저승 이야기' },
      { word: '국제시장', hint: '아버지의 시대' },
      { word: '베테랑', hint: '재벌과 싸우는 형사' },
      { word: '도둑들', hint: '카지노를 터는 도둑들' },
      { word: '7번방의선물', hint: '아빠와 딸의 감동 이야기' },
      { word: '광해', hint: '왕이 된 남자' },
      { word: '왕의남자', hint: '광대 이야기' },
      { word: '암살', hint: '독립군 저격수' },
      { word: '부산행', hint: '좀비 기차 영화' },
      { word: '해운대', hint: '쓰나미 재난 영화' },
      { word: '괴물', hint: '한강의 괴물' },
      { word: '실미도', hint: '북파 공작원' },
      { word: '태극기휘날리며', hint: '한국전쟁의 형제' },
      { word: '범죄도시', hint: '마동석의 액션' },
      { word: '아바타', hint: '판도라 행성' },
      { word: '타이타닉', hint: '거대 여객선의 침몰' },
      { word: '어벤져스', hint: '마블 히어로 총출동' },
      { word: '인터스텔라', hint: '우주 SF 명작' },
      { word: '겨울왕국', hint: '엘사와 안나' },
      { word: '라이온킹', hint: '심바의 성장기' },
      { word: '토이스토리', hint: '장난감들의 모험' },
      { word: '라라랜드', hint: '재즈 뮤지컬 영화' },
    ],
  },
  daily: {
    name: '생활',
    emoji: '🏠',
    words: [
      { word: '냉장고', hint: '음식을 차갑게 보관해요' },
      { word: '세탁기', hint: '빨래를 해줘요' },
      { word: '청소기', hint: '먼지를 빨아들여요' },
      { word: '에어컨', hint: '여름 필수품' },
      { word: '텔레비전', hint: '드라마를 봐요' },
      { word: '컴퓨터', hint: '인터넷을 해요' },
      { word: '스마트폰', hint: '항상 손에 들고 다녀요' },
      { word: '이어폰', hint: '음악을 들을 때 써요' },
      { word: '안경', hint: '시력을 보정해줘요' },
      { word: '우산', hint: '비올 때 펴요' },
      { word: '가방', hint: '물건을 담아 다녀요' },
      { word: '지갑', hint: '돈과 카드를 넣어요' },
      { word: '시계', hint: '시간을 알려줘요' },
      { word: '거울', hint: '나를 비춰봐요' },
      { word: '베개', hint: '잘 때 머리 밑에 두어요' },
      { word: '이불', hint: '잘 때 덮어요' },
      { word: '치약', hint: '양치할 때 써요' },
      { word: '칫솔', hint: '이를 닦아요' },
      { word: '비누', hint: '손을 씻을 때 써요' },
      { word: '수건', hint: '몸을 닦아요' },
      { word: '의자', hint: '앉을 때 써요' },
      { word: '책상', hint: '공부할 때 써요' },
      { word: '화장실', hint: '볼 일을 봐요' },
      { word: '주방', hint: '요리하는 곳' },
      { word: '엘리베이터', hint: '층을 오르내리는 기계' },
    ],
  },
};

// 한글 초성 추출 함수
function getChosung(text) {
  const CHO = ['ㄱ','ㄲ','ㄴ','ㄷ','ㄸ','ㄹ','ㅁ','ㅂ','ㅃ','ㅅ','ㅆ','ㅇ','ㅈ','ㅉ','ㅊ','ㅋ','ㅌ','ㅍ','ㅎ'];
  let result = '';
  for (const ch of text) {
    const code = ch.charCodeAt(0);
    if (code >= 0xAC00 && code <= 0xD7A3) {
      const idx = Math.floor((code - 0xAC00) / 588);
      result += CHO[idx];
    } else {
      result += ch;
    }
  }
  return result;
}
